spring.application.name=e-commerce-order-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#configure JPA/hibernate to auto create tables
#the "update" config will keep the existing data in the table
spring.jpa.hibernate.ddl-auto=update
